### ISSUE TITLE
expose option for # or #! in front of route for iso

### ISSUE THREAD

**Issue by rmfarrell** [static-dev/spike#106]
for `iso` there should be an option for the route to use the `#` in front of the route. This is used by default for routers in other frameworks (e.g. Angular/Vue) because unless you're intercepting the request on your web server, it will return a 404. 

On S3, for example, there is no way to intercept the request.

**Comment by jescalan** [comment]
The page is actually there for all routes though, so there's no need to intercept it 😁

**Comment by rmfarrell** [comment]
there might be some other reason to use it though, for example you want an element in the global header to persist even as you navigate from view to view

**Comment by jescalan** [comment]
So we thought about this, but at the moment what `iso` mode does is pulls a full html page rendered and writes it to the document root. So you couldn't actually pull that off unless your other html page didn't include the header, which would make it not render correctly standalone.

Generally our thoughts were that for more complex use cases with partial page renders, it would be better to do something like using vue.js or another SPA framework. This is just for making vanilla static page loads super fast.

**Comment by rmfarrell** [comment]
👍  makes sense
