### ISSUE TITLE
Silent fail on global config access

### ISSUE THREAD

**Issue by jescalan** [static-dev/spike#15]
If there is a permission error read/writing the global config as it relates to the analytics initialization, it should log a warning rather than crashing.

**Comment by argyleink** [comment]
that what i'm seeing here?

![screen shot 2016-07-06 at 5 51 29 pm](https://cloud.githubusercontent.com/assets/1134620/16639212/543ad366-43a2-11e6-8bd3-5185fdf2e3d4.png)
