### ISSUE TITLE
Image broken on `spike compile -e production`

### ISSUE THREAD

**Issue by muhajirdev** [static-dev/spike#29]
When compile with `spike compile` everything works perfectly.
But when i compilie with `spike compile -e production` the image is broken.
I can't open it with my browser or my image viewer.

![screenshot from 2016-09-13 11-02-47](https://cloud.githubusercontent.com/assets/12745166/18461583/64876b7e-79a5-11e6-9a07-06fca0a4d976.png)
![screenshot from 2016-09-13 11-04-04](https://cloud.githubusercontent.com/assets/12745166/18461594/840bcf76-79a5-11e6-944e-78ffee6cec5c.png)

Here's my test repo https://github.com/muhajirframe/spike-test . I change nothing in it. I just put image inside assets/img and reference it in views/index.sgr
Tried with fresh install of spike v 0.12.1 
node version 6.5.0
OS Ubuntu

**Comment by robertguss** [comment]
Hi muhajirframe,

So I have found the problem and it has to do with the following line in your app.production.js file, beginning on line 16. 

``` js
module: {
    loaders: [{ test: /\.(jpe?g|png|gif|svg)$/i, loader: 'source-loader!image-webpack' }]
  },
```

Replace it with the following, which is the default when you first initialize a new spike project and a production file. 

``` js
module: {
    loaders: [{ test: /\.(jpe?g|png|gif|svg)$/i, loader: 'image-webpack' }]
  },
```

**Comment by jescalan** [comment]
Looks about right, thanks for the help here @robertguss!
