### ISSUE TITLE
[For @next] Updates to production config needed

### ISSUE THREAD

**Issue by mwickett** [static-dev/spike#55]
Looks like `offline-plugin` needs to be included as a dev-dep, or else removed from production config.

Based on [this](https://webpack.js.org/guides/migrating/#dedupeplugin-has-been-removed) I think `dedupeplugin` can be removed from production config as well.

Let me know, happy to make PR (even though it's tiny)

**Comment by jescalan** [comment]
Would be great, thank you!

**Comment by mwickett** [comment]
Realize this should be over in `spike-tpl-base`. Sorry.
