### ISSUE TITLE
Opt-out of Analytics not working

### ISSUE THREAD

**Issue by andystevensname** [static-dev/spike#56]
Running the command `spike analytics disable` fails:

    $ spike analytics disable
    usage: spike [-h] [-v] {compile,watch,clean,new,template,tpl} ...
    spike: error: Invalid choice: analytics (choose from [compile, watch, clean, new, template, tpl])

**Comment by jescalan** [comment]
Sorry, I haven't yet added an analytics opt out command. Actually, the analytics aren't working at all, sadly, see #27. Just not quite a priority yet!
