### ISSUE TITLE
Reshape and syntax highlighting

### ISSUE THREAD

**Issue by alexpate** [static-dev/spike#58]
Is it possible to get syntax highlighting working with reshape/markdown-it?

Using the out-of-the-box config with `spike-html-standards`.

**Comment by jescalan** [comment]
Yeah definitely! You'd just have to pass a highlighter to the `markdown` option ([ref](https://github.com/reshape/standard#options)) in reshape-standard.

Docs for the highlight option: https://github.com/markdown-it/markdown-it#syntax-highlighting
