### ISSUE TITLE
Filepath for layout.sgr

### ISSUE THREAD

**Issue by robertguss** [static-dev/spike#62]
I am just following along with the quickstart here:
https://spike.readme.io/docs/quick-start

When I ran the command spike watch, I received an error:
"Module build failed: Error: ENOENT: no such file or directory, open '/Users/rguss/Projects/Spike/test-project/layout.sgr'"

Inside of index.sgr:
extends(src='layout.sgr')

I fixed the error by changing the src to:
extends(src='views/layout.sgr')

If you want I can submit a pull request with this minor change, I am more than happy to ;)

**Comment by jescalan** [comment]
Hey Robert, thanks for catching this!

Hmm... so this shouldn't be the case. Views will resolve layouts relative to their own path, or at least they should be. I just tried this out locally, creating a fresh project, running `spike watch`, and making a few changes to different files and didn't get any errors.

Could you give me some more details on your operating system and the project you're working with? Was it just the default template with no changes, or did you make some changes?

**Comment by robertguss** [comment]
Hey Jeff,
I am running:
 Mac 10.12.4
Node 6.9.4

I didn't make any changes, I was just going through the guide and when the browser popped up, it said cannot GET /
I then open the code and found the path was wrong.

I just did a fresh install again without changing any files and still got the same error.

**Comment by jescalan** [comment]
That is very strange, I'm running the same version of osx -- only difference is that I'm on node v7. I can't imagine this really makes the difference, but just in case, is there any chance you could test with node v7?

Otherwise I'm baffled as to how this could happen, and there isn't really a way for me to debug it unless I can reproduce!

**Comment by robertguss** [comment]
I just installed and tried on Node 7.9.0 and same thing. Must be something odd on my machine, which I am frankly ok with. I just wanted to make sure it wasn't a bug, if it were I would send a pull request.

**Comment by jescalan** [comment]
Wow, that is super strange. I can't imagine what it could be! If you have a chance, is there any way you could test it out on a friend/coworker's machine and see if it works? If so we can confirm that it's something specific to your setup...

**Comment by robertguss** [comment]
very. I will test on my home machine and let you know.

**Comment by robertguss** [comment]
Hey Jeff,
So I finally managed to figure out what the issue was. I installed spike by running 'yarn global add spike'. Yarn was causing the issues. Once I removed and did 'npm i -g spike' everything worked as expected. So all is well.

**Comment by jescalan** [comment]
Huh, that is really strange. I wonder why! I have also had issues with yarn global installs but not anything like this. Well, I'm glad it was worked out, thanks for the update!
