### ISSUE TITLE
HTML as root view instead of SugarML?

### ISSUE THREAD

**Issue by aesop1** [static-dev/spike#65]
I'm unclear via the documentation if I can use a plain HTML file (with include files) instead of SugarML.

Can I do this or does some configuration need to take place first.

I can include an HTML file from a SugarML file, but I can't seem to include HTML inside of HTML (or use variables, etc.)

**Comment by jescalan** [comment]
You absolutely can, we have a template for this specifically:

https://github.com/static-dev/spike-tpl-sugarfree

If you want to use non-html features like includes, locals, etc, you need to run it through reshape. The template above shows how to do this (basically, pass `parser: false`) to your reshape config and that's it.
