### ISSUE TITLE
Demo template generates mangled html

### ISSUE THREAD

**Issue by knupska** [static-dev/spike#68]
Executing a `spike compile` with a fresh pull results in the demo template compiling some gnarly looking html with two issues:

1. The quotes for the spike links href are being eaten by the typographic quote system and converted to left/right single quote characters (switching it out for `"` in `index.sgr` just results in them being converted to left/right double quotes).

2. The markdown demonstration paragraph is wrapped in another paragraph.

```
<main role="main" id="index">
  <h2>Hello World!</h2>
  <p>Thanks for using <a href=‘https://github.com/static-dev/spike’>spike</a></p>
  <p>Example of locals: bar</p>
  <p>
    <p>Example of <strong>markdown</strong></p>
  </p>
```

**Comment by jescalan** [comment]
Good catch, sorry about that! I'll fix this in a moment

**Comment by jescalan** [comment]
@knupska Fixed! Thanks again for catching this 😁
