### ISSUE TITLE
spike template list doesn't work

### ISSUE THREAD

**Issue by bangzek** [static-dev/spike#75]
```
$ spike template list
✓ [object Object]
$ spike -v
2.0.2
$ node -v
v6.11.1
```

**Comment by jescalan** [comment]
Oh man, not sure how I didn't notice that one or catch it in a test! Good call. Will have this fixed by tomorrow.

**Comment by bangzek** [comment]
Still no fixes on v2.2

```
$ spike template list
✓ [object Object]
$ spike -v
2.2.0
$ node -v
v6.11.2
```

**Comment by jescalan** [comment]
I'm sorry, I just haven't had time. It would be really great if you would be willing to look in to contributing here! Shouldn't be a difficult fix.

**Comment by jescalan** [comment]
Actually just managed to fix it. Will be out next release
