### ISSUE TITLE
error when layout is in another subfolder

### ISSUE THREAD

**Issue by crivera** [static-dev/spike#81]
Hi

i have the following folder structure:

- views
  - layouts
    - layout.html
  - fragments
    - header.html
    - footer.html
  - search
    - result.html
  - index.html

in result.html i am trying to add the layout.html like this:

<extends src='../layouts/layout.html'>

which works fine

in index.html i am trying to add the layout.html like this:

<extends src='./layouts/layout.html'>

which then gives me an error because in layout.html i refer to the header and footer like this:

<include src='../fragments/header.html'></include>

it seems like the path always goes from the current path of the file instead of the one from where i am at. does that make sense?

in result.html it works fine because ../fragments/header.html is a valid path.
in index.html it does not work fine because ../fragments/header.html does not exist (its going above the views folder)

do you guys have an idea how to fix that without creating multiple layout files?

**Comment by jescalan** [comment]
Yep, you can use the `root` option in `htmlStandards` to resolve from an absolute path 😁 

https://github.com/reshape/standard#options

**Comment by crivera** [comment]
awesome that worked !
