### ISSUE TITLE
Install hanging on ua-parser-js

### ISSUE THREAD

**Issue by smth** [static-dev/spike#86]
Trying to install Spike for the first time, it's stuck on
```
fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/ua-parser-js
```
It's been like an hour, I guess that's not normal?

**Comment by jescalan** [comment]
Definitely not normal, however, this is an issue with either your internet connection or NPM, and is out of spike's control entirely 😢

**Comment by smth** [comment]
Wasn't my internet connection. Not sure what it was, but switching from Node 7 to 8, and updating NPM seemed to get it working.
