### ISSUE TITLE
Cache busting CSS?

### ISSUE THREAD

**Issue by vwong** [static-dev/spike#89]
I noticed the JS bundles had cache-busting filenames in production, but the CSS bundles do not.  How do I achieve the latter?

I noticed in the default `layout.sgr`, we have:
```
    link(rel='stylesheet' href='css/index.css')
```
and 
```
    block(name='javascript')
      script(src='js/main.js' defer)
```
It turns out `js/main.js` is defined in [spike-core](https://github.com/static-dev/spike-core/blob/master/lib/config.js#L57), but I can't seem to find the corresponding one for CSS.

Is there some trick with [ExtractTextPlugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) that I might be able to use?

**Comment by jescalan** [comment]
Hey @vwong!

So, extract-text-plugin isn't really compatible with spike - adding this feature would mean a few modifications to the core code. If you're interested in contributing, I'd be more than happy to walk through this with you!
