### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by DirtyF** [static-dev/spike#91]
What is Spike licensed under?

**Comment by jescalan** [comment]
Haha you really didn't look too hard did you?

https://github.com/static-dev/spike/blob/master/license.md
https://github.com/static-dev/spike/blob/master/package.json#L40

**Comment by DirtyF** [comment]
@jescalan [Spike is now listed on thenewdynamic](https://github.com/thenewdynamic-org/thenewdynamic.org/blob/hugo/content/tool/spike.md) 😉

**Comment by jescalan** [comment]
Whoo! Thank you! 🎉
