### ISSUE TITLE
Roots-Mini's babel/babylon is parsing .ttf files

### ISSUE THREAD

**Issue by EnMod** [static-dev/spike#94]
Not exactly sure why, but they went right for my `enmod.ttf` file!  Here's my error output:

```
Potentially unhandled rejection [1] SyntaxError: /home/vagrant/GitHub/noelquiles.com/assets/css/fonts/enmod.ttf: Unexpected character '' (1:0)
> 1 |      FFTMgï¿½ï¿½ï¿½   GDEFX  8 OS/2b MA XVcmapï¿½Aes ï¿½ rcvt  ï¿½ ï¿½ $
    | ^
  2 | fpgmSï¿½/ï¿½ 0 egasp ï¿glyfï¿½Jï¿½ï¿½ï¿½8head P - ï¿½6hheaï¿½ï¿½  $hmtx
ï¿½
  3 | ï¿½ 4ï¿½loca`fd  ï¿½Xmaxp Fs 8 name '2  X Lpost7ï¿½"N ï¿½ï¿½prepï¿½ï¿½%' ï¿½bwebfï¿½ï¿½Qï¿½  ï¿½=ï¿½ï¿½Í¥ï¿½ï¿½Í¦i4    *     ] ï¿½ 2ï¿½  2ï¿½ ï¿½f
         PfEd@
  4 | ï¿½ fï¿½`     l    P
    at Parser.pp.raise (/usr/lib/node_modules/roots-mini/node_modules/babylon/index.js:1378:13)
    at Parser.getTokenFromCode (/usr/lib/node_modules/roots-mini/node_modules/babylon/index.js:5250:10)
    at Parser.readToken (/usr/lib/node_modules/roots-mini/node_modules/babylon/index.js:4887:19)
    at Parser.nextToken (/usr/lib/node_modules/roots-mini/node_modules/babylon/index.js:4877:19)
    at Parser.parse (/usr/lib/node_modules/roots-mini/node_modules/babylon/index.js:1348:10)
    at Object.parse (/usr/lib/node_modules/roots-mini/node_modules/babylon/index.js:45:50)
    at File.parse (/usr/lib/node_modules/roots-mini/node_modules/babel-core/lib/transformation/file/index.js:479:24)
    at File.parseCode (/usr/lib/node_modules/roots-mini/node_modules/babel-core/lib/transformation/file/index.js:568:20)
    at /usr/lib/node_modules/roots-mini/node_modules/babel-core/lib/transformation/pipeline.js:48:12
    at File.wrap (/usr/lib/node_modules/roots-mini/node_modules/babel-core/lib/transformation/file/index.js:528:16)
xtermxtermxtermxtermxtermxtermxtermxterm
```

**Comment by kylemac** [comment]
@EnMod I added a `.ttf` file to my local project's `assets/css/fonts` dir and i didn't get any errors. maybe if you share your `app.js` we can see if maybe there's some other configuration thats causing it?

**Comment by kylemac** [comment]
oh, also worth asking: which version of `roots-mini` are you using? I tested with the latest version `0.0.22`. there were some improvements to the way we handled static files in `0.0.19`+

**Comment by kylemac** [comment]
@EnMod still an issue? if not, we'll close but feel free to file any other issues you come across

**Comment by EnMod** [comment]
@kylemac Been a very busy week so I haven't tested, but I'll update this comment with my results later today.  Thanks for looking into this!

**Comment by kylemac** [comment]
no sweat. let us know

**Comment by EnMod** [comment]
Well...this is unfortunate.  Updating to the latest `roots-mini` has made it so this error pops up from the tool's config:
```
/home/enmod/.npm-global/lib/node_modules/roots-mini/lib/config.js:269
    if (err.code !== 'ENOENT') { throw new Error(err) }
                                 ^

Error: SyntaxError: Unexpected token import
    at loadFile (/home/enmod/.npm-global/lib/node_modules/roots-mini/lib/config.js:269:40)
    at Config.parseAppJs (/home/enmod/.npm-global/lib/node_modules/roots-mini/lib/config.js:251:18)
    at new Config (/home/enmod/.npm-global/lib/node_modules/roots-mini/lib/config.js:31:38)
    at new Roots (/home/enmod/.npm-global/lib/node_modules/roots-mini/lib/index.js:30:19)
    at module.exports (/home/enmod/.npm-global/lib/node_modules/roots-mini/lib/cli/watch.js:2:19)
    at CLI.run (/home/enmod/.npm-global/lib/node_modules/roots-mini/lib/cli/index.js:47:21)
    at Object.<anonymous> (/home/enmod/.npm-global/lib/node_modules/roots-mini/bin/roots:30:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

**Comment by jescalan** [comment]
@EnMod covered in the release notes!

https://github.com/static-dev/spike/releases/tag/v0.0.23

Note that since we're on a very early release cycle, *any release could be breaking*. Make sure to check the release notes before upgrading 😁

**Comment by kylemac** [comment]
@EnMod we updated to enforce node 6. this means you'll need to update your `app.js`. you should be able to replace your `import foo from 'bar'` with `const foo = require('bar')` to get things working. 

ref: https://github.com/static-dev/spike/releases/tag/v0.0.23

**Comment by jescalan** [comment]
You will also need to replace `export default` with `module.exports = `

This early on we will frequently have breaking releases, so make sure to check the release notes when upgrading just in case!

**Comment by kylemac** [comment]
we're going to try and keep those breaking changes to a minimum though!

**Comment by EnMod** [comment]
Good call, everyone!  I have been moving pretty fast as of late so I admittedly haven't been checking the release notes, I'll be sure to keep in mind the alpha nature of this project for the time being.

**Comment by kylemac** [comment]
we're stoked you're checking it out. we feel like we'll stabilize pretty soon, so hang with us! and let us know if there are features you want to support that we haven't yet.

**Comment by kylemac** [comment]
and so you know, we're using it on some client projects at the moment - so it won't devolve into something unusable : )

**Comment by EnMod** [comment]
Thanks @kylemac ! I'm definitely looking forward to a stable version of `spike` as I proceed.  I've been using Roots since the move to v3, so I'm well aware of how hard you all work on your tools, it's the reason I've stuck around and haven't really switched away since I switched from DocPad :+1: 

The `rooftop-cms` integration takes care of the one request I was going to add, that being integration of an API-first CMS like Contentful.  I suppose I will also add that integrating something similar to `ship` would be a great time-saver in the future.  Other than that I'm ready and waiting for future developments :smile:

**Comment by jescalan** [comment]
@EnMod 💖 - we're shooting towards it as quick as we can. rooftop is a pretty big for us, it's something we're really looking forward to building more heavily on top of. we've been working closely with their developers, and will make sure we have an ideal cms workflow in place. as far as `ship`, honestly it's a little less likely, as we bank pretty heavily on [netlify](https://www.netlify.com/) for our static hosting, and it's done an incredible job of accommodating all our needs. Have you tried it?

**Comment by EnMod** [comment]
@jescalan that sounds great, good to see that there's a focus on ideal CMS workflow.  Rolling my own with Contentful hasn't been the greatest experience, and Rooftop seems to be the best way to improve that.  

As for netlify, I have tried it, but I'm incredibly money-conscious and am not ready yet to pay $7.50/month/site just to remove their Netlify callout (the only thing that bugs me about their free tier at the moment).  I get by running a VPS and leveraging any other tech I can find that saves me more haha, as most client work isn't hosted by me.  If I only wanted to run one site on Netlify I suppose I could get used to the callout, but even then I'm not too keen on it.

**Comment by kylemac** [comment]
@EnMod totally reasonable feedback. i think deployment will get back on our roadmap. i believe it was a feature that made roots really great. i think when we do readdress deployment, we'll just try to control the scope of it a little more. `ship` tried to solve the problem for everyone - we may be better suited just supporting a few use-cases.
