### ISSUE TITLE
Uglify JS minification issue

### ISSUE THREAD

**Issue by smuemd** [static-dev/spike#98]
Hello I ran into a bug when compiling this this libary (https://github.com/porsager/bss/issues/18) in production mode

I am getting this:

```bash
{ Error: 4.714f43602dc9cdd1454a.js from UglifyJs
Unexpected token: operator (>) [4.714f43602dc9cdd1454a.js:29,12]
```

here is the original issue: https://github.com/porsager/bss/issues/18

looks like the below two lines:

https://github.com/static-dev/spike-core/blob/a2743fb7197a780be5e63fc641b7bb25c7813dd8/lib/config.js#L117

https://github.com/static-dev/spike-core/blob/a2743fb7197a780be5e63fc641b7bb25c7813dd8/lib/config.js#L227

Cause babel-loader to exclude the node_modules folder, thus also exclude the installed bss module, so bss kept as ES6 module untouched, then lead to the uglify error.

Solution could be to remove the exclude rule for babel-loader, but not sure about side effects in spike.

**Comment by jescalan** [comment]
Running babel on every node module is absolutely brutal, takes ages, and is unnecessary for nearly all of them, which is why I have it set up that way. Afaik though, if you require into one of your bundles, it should be transpiled, and also it looks like [the main output for this project](https://github.com/porsager/bss/blob/master/bss.js) is already pre-transpiled, so I'm a little confused about why this might be happening.

**Comment by smuemd** [comment]
Confuses me too. It seems like webpack doesn't transpile when there is a module field in the package.json. Which sort of kind of is understandable. But then Uglify will trip over it as it doesnt process modern JS

I guess this is one to just sit out until spike dependencies are updated down the line.
Do you have an update in the pipeline? Need help with that?

**Comment by jescalan** [comment]
Unfortunately I don't at all - since I changed jobs I have hardly had any time at all to work on spike :(

**Comment by smuemd** [comment]
Fair enough. Migrating to Webpack 4 probably will not be straightforward, considering all the changes. The pace that this stuff evolves at is quite breathtaking. And spike is quite solid as is for the time being. No reason to rush things.

**Comment by jescalan** [comment]
Yeah, migrating to 4 will be brutal for sure. Going from 2 to 3 was extremely difficult. It is definitely something I plan on doing, but just won't be able to get to it for a bit until things calm down at my full time job.
